### ISSUE TITLE
:main is not allowed to have dash in its name when using component-restart

### ISSUE THREAD

**Issue by BeneStem** [lomin/component-restart#1]
Moin Steven,

we had an issue when using a dashed name for our main class, e.g "test-core".
The auto restart did not work then and threw an exception.
Fixed it by using a non dashed name.
I was stupid and did not save the exception... sorry!

Maybe you can provide an update that can handle dashed names.

If you have further questions Christian and I are sitting in Geb3 now :) 

Thank you very much for you help!
Greetz
/ben

**Comment by lomin** [comment]
Hi Bene,

no worries about the exception, I will look into it.

Cheers,
Steven

2016-06-29 20:07 GMT+02:00 Benedikt Stemmildt <notifications@github.com>:

> Moin Steven,
>
> we had an issue when using a dashed name for our main class, e.g
> "test-core".
> The auto restart did not work then and threw an exception.
> Fixed it by using a non dashed name.
> I was stupid and did not save the exception... sorry!
>
> Maybe you can provide an update that can handle dashed names.
>
> If you have further questions Christian and I are sitting in Geb3 now :)
>
> Thank you very much for you help!
> Greetz
> /ben
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lomin/component-restart/issues/1>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAMkBjOz7JHY8o0jwOvOxxCbBUBLHkSZks5qQrRlgaJpZM4JBaOk>
> .
>



-- 
Steven Collins

persönlich: +49 172 429 76 97
zentral: +49 40 413 584 80

it-agile GmbH, Große Elbstraße 273, D-22767 Hamburg
Handelsregister Hamburg, HRB 92261, Geschäftsführer: Henning Wolf, Stefan
Roock
http://www.it-agile.de

Agil Skalieren nach Maß: www.it-agile.de/skalieren-nach-mass

**Comment by lomin** [comment]
Fixed in version 0.1.1.

**Comment by briemens** [comment]
Hey @Lomin,

I'm using version 0.1.1, but I still get an error when using a dash in a namespace.

Dependency in project.clj
```
[me.lomin/component-restart "0.1.1"]
```

Stack trace:
```
Caused by: java.lang.Exception: No namespace: crafity_admin.core found
        at clojure.core$the_ns.invokeStatic(core.clj:4032)
        at clojure.core$ns_resolve.invokeStatic(core.clj:4239)
        at clojure.core$ns_resolve.invokeStatic(core.clj:4229)
        at clojure.core$ns_resolve.invoke(core.clj:4229)
        at me.lomin.component_restart$resolve_callback.invokeStatic(component_restart.clj:31)
        at me.lomin.component_restart$resolve_callback.invoke(component_restart.clj:27)
        at me.lomin.component_restart$reload.invokeStatic(component_restart.clj:38)
        at me.lomin.component_restart$reload.invoke(component_restart.clj:33)
        at me.lomin.component_restart$watch.invokeStatic(component_restart.clj:48)
        at me.lomin.component_restart$watch.invoke(component_restart.clj:40)
        at me.lomin.component_restart$watch.invokeStatic(component_restart.clj:42)
        at me.lomin.component_restart$watch.invoke(component_restart.clj:40)
        at crafity_admin.core$_main.invokeStatic(core.clj:32)
        at crafity_admin.core$_main.doInvoke(core.clj:30)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at user$eval11954.invokeStatic(form-init6788740823694068107.clj:1)
        at user$eval11954.invoke(form-init6788740823694068107.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 14 more
```

**Comment by lomin** [comment]
Hi @briemens,

thanks for reporting this error. There was an issue with underscores in packages. I released a new version 0.1.2 which fixes that.

Cheers,
Steven
